const redirects = {
  "antica-audio": "https://discoverygubbio.com/antica-audio",
  "cante": "https://discoverygubbio.com/cante",
  "capitano": "https://discoverygubbio.com/capitano",
  "cante": "https://discoverygubbio.com/casagabrielli",
  "ducale": "https://discoverygubbio.com/ducale",
  "duomobotte": "https://discoverygubbio.com/duomobotte",
  "fontanamatti": "https://discoverygubbio.com/fontana",
  "giardinipensili": "https://discoverygubbio.com/giardini",
  "medievale-audio": "https://discoverygubbio.com/medievale-audio",
  "muratori": "https://discoverygubbio.com/muratori",
  "piazzagrande": "https://discoverygubbio.com/piazzagrande",
  "pietrone": "https://discoverygubbio.com/pietrone",
  "portamorto": "https://discoverygubbio.com/portamorto",
  "rinascimentale-audio": "https://discoverygubbio.com/rinascimentale-audio",
  "ripa": "https://discoverygubbio.com/ripa",
  "sanfrancesco": "https://discoverygubbio.com/sanfrancesco",
  "sangiovanni": "https://discoverygubbio.com/sangiovanni",
  "santubaldo": "https://discoverygubbio.com/santubaldo",
  "tavole": "https://discoverygubbio.com/tavole",
  "teatroromano": "https://discoverygubbio.com/teatroromano",
  "vitafrancesco": "https://discoverygubbio.com/francesco",
};
